apiVersion: v1
kind: Service
metadata:
  name: hw-load-balancer
  namespace: argo-hello-world
spec:
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
