apiVersion: v1
kind: Ingress
metadata:
  name: hw-ingress
spec:
  rules:
  - host: hw-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              name: web
              number: 80