apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: argo-hello-world
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
  selector:
    app: hello-world

spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
