apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-configmap
  namespace: argo-hello-world
data:
  # Key-value pairs
  APP_ENV: "production"
  APP_DEBUG: "false"
  HOSTNAME: "pizza"
  hostname: "pizza"