apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-app
  namespace: argo-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
        - name: hello-world
          image: rancher/hello-world:latest
          ports:
            - containerPort: 80
          valueFrom:
            - configMapRef:
                name: hw-configmap
